export enum NotificationType {
  DONATION_STATUS_UPDATED = 'DONATION_STATUS_UPDATED',
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  NEW_MESSAGE = 'NEW_MESSAGE',
  CAMPAIGN_UPDATE = 'CAMPAIGN_UPDATE',
  CAMPAIGN_GOAL_REACHED = 'CAMPAIGN_GOAL_REACHED',
}
